videojueguitos/api_arcade/src/Entity/Juegos.php
<?php

namespace App\Entity;

use App\Repository\JuegosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JuegosRepository::class)]
class Juegos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 45)]
    private ?string $nombre = null;

    #[ORM\Column(length: 125, nullable: true)]
    private ?string $descripcion = null;

    #[ORM\Column(nullable: true)]
    private ?int $votos_positivos = null;

    #[ORM\Column(nullable: true)]
    private ?int $votos_negativos = null;

    #[ORM\Column(type: Types::BLOB, nullable: true)]
    private $imagen;

    #[ORM\ManyToMany(targetEntity: Genero::class, inversedBy: 'juegos')]
    private Collection $generos;

    public function __construct()
    {
        $this->generos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): static
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getVotosPositivos(): ?int
    {
        return $this->votos_positivos;
    }

    public function setVotosPositivos(?int $votos_positivos): static
    {
        $this->votos_positivos = $votos_positivos;

        return $this;
    }

    public function getVotosNegativos(): ?int
    {
        return $this->votos_negativos;
    }

    public function setVotosNegativos(?int $votos_negativos): static
    {
        $this->votos_negativos = $votos_negativos;

        return $this;
    }

    public function getImagen()
    {
        return $this->imagen;
    }

    public function setImagen($imagen): static
    {
        $this->imagen = $imagen;

        return $this;
    }

    /**
     * @return Collection<int, Genero>
     */
    public function getGeneros(): Collection
    {
        return $this->generos;
    }

    public function addGenero(Genero $genero): static
    {
        if (!$this->generos->contains($genero)) {
            $this->generos->add($genero);
        }

        return $this;
    }

    public function removeGenero(Genero $genero): static
    {
        $this->generos->removeElement($genero);

        return $this;
    }
}

videojueguitos/api_arcade/src/Form/JuegosType.php
<?php

namespace App\Form;

use App\Entity\Genero;
use App\Entity\Juegos;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JuegosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre', null, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('descripcion', null, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('votos_positivos', null, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('votos_negativos', null, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('imagen', FileType::class, [
                'data_class' => null,
                'required' => false,
                'attr' => ['class' => 'form-control']
            ])
            ->add('generos', EntityType::class, [
                'class' => Genero::class,
                'choice_label' => 'nombre',
                'multiple' => true,
                'expanded' => true,
            ]);
    }
}    

videojueguitos/api_arcade/templates/juegos/_delete_form.html.twig
<form method="post" action="{{ path('app_juegos_delete', {'id': juego.id}) }}" onsubmit="return confirm('¿Estás seguro de que quieres eliminar este juego?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ juego.id) }}">
    <button class="btn btn-danger" type="submit">Eliminar</button>
</form>

videojueguitos/api_arcade/templates/juegos/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
   <button type="submit" class="btn btn-primary">{{ button_label|default('Crear Juego') }}</button>
{{ form_end(form) }}

videojueguitos/api_arcade/templates/juegos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Juegos{% endblock %}

{% block body %}
    <h1>Edit Juegos</h1>

    {{ include('juegos/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_juegos_index') }}" class="btn btn-secondary mt-3">Vover a juegos</a>
<br>
    {{ include('juegos/_delete_form.html.twig') }}
{% endblock %}

videojueguitos/api_arcade/templates/juegos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lista de Juegos{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1>Lista de Juegos</h1>
        <a href="{{ path('app_juegos_new') }}" class="btn btn-success">Crear</a>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Votos positivos</th>
                    <th scope="col">Votos negativos</th>
                    <th scope="col">Imagen</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for juego in juegos %}
                    <tr>
                        <td>{{ juego.id }}</td>
                        <td>{{ juego.nombre }}</td>
                        <td>{{ juego.descripcion }}</td>
                        <td>{{ juego.votosPositivos }}</td>
                        <td>{{ juego.votosNegativos }}</td>
                        <td>{{ juego.imagen }}</td>
                        <td>
                            <div class="btn-group">
                                <a href="{{ path('app_juegos_show', {'id': juego.id}) }}" class="btn btn-info btn-sm">Ver</a>
                                <a href="{{ path('app_juegos_edit', {'id': juego.id}) }}" class="btn btn-primary btn-sm">Editar</a>
                            </div>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7">No se encontraron registros</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

videojueguitos/api_arcade/templates/juegos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuevo Juego{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1>Crear Juego</h1>

        {{ include('juegos/_form.html.twig') }}

        <a href="{{ path('app_juegos_index') }}" class="btn btn-secondary mt-3">Volver a Juegos</a>
    </div>
{% endblock %}

videojueguitos/api_arcade/templates/juegos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Juego{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1>Juego</h1>

        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">Id</th>
                    <td>{{ juego.id }}</td>
                </tr>
                <tr>
                    <th scope="row">Nombre</th>
                    <td>{{ juego.nombre }}</td>
                </tr>
                <tr>
                    <th scope="row">Descripcion</th>
                    <td>{{ juego.descripcion }}</td>
                </tr>
                <tr>
                    <th scope="row">Votos positivos</th>
                    <td>{{ juego.votosPositivos }}</td>
                </tr>
                <tr>
                    <th scope="row">Votos negativos</th>
                    <td>{{ juego.votosNegativos }}</td>
                </tr>
                <tr>
                    <th scope="row">Imagen</th>
                    <td>{{ juego.imagen }}</td>
                </tr>
            </tbody>
        </table>

        <a href="{{ path('app_juegos_index') }}" class="btn btn-secondary">Volver a juegos</a>
        <a href="{{ path('app_juegos_edit', {'id': juego.id}) }}" class="btn btn-primary">Editar</a>

        {{ include('juegos/_delete_form.html.twig') }}
    </div>
{% endblock %}